#!/bin/bash

## iterm2
brew install --cask iterm2
## jq
brew install jq
## yq
brew install yq
## fzf 
brew install fzf
## ripgrep
brew install ripgrep
## node
brew install node
## tmux
brew install tmux
## neovim
brew install neovim
## web browser
brew install --cask arc
## notes
brew install --cask obsidian
## yabai - window/space manager - switched out while trying aerospace
# brew install koekeishiya/formulae/yabai
# yabai --start-service - switched out while trying aerospace
## skhd - yabai hotkeys
# brew install koekeishiya/formulae/skhd - switched out while trying aerospace
# skhd --start-service - switched out while trying aerospace
# aerospace - window/space manager
brew install --cask nikitabobko/tap/aerospace
brew install --cask font-jetbrains-mono-nerd-font
