#!/bin/bash

function create_symlink() {
  local source_path=$1
  local target_path=$2
  if [ ! -e "$target_path" ]; then
    ln -s "$source_path" "$target_path"
  else
    echo "already exists: file or link at $target_path"
  fi
}

create_symlink "$HOME/dotfiles/.tmux.conf" "$HOME/.tmux.conf"
create_symlink "$HOME/.dotfiles/.zshrc" "$HOME/.zshrc"
create_symlink "$HOME/.dotfiles/.config" "$HOME/.config"

mkdir -p $HOME/.config/tmux/sessions
# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true
# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false
# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0
# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false
# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
# Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5
# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0
# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0
## xcode command line tools
xcode-select --install
## homebrew
sudo curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash < /dev/null
if [ ! -f /opt/homebrew/bin/brew ]; then
    echo "No file found at /opt/homebrew/bin/brew"
    exit 1
fi
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
if ! command -v brew &> /dev/null; then
    echo "homebrew could not be found. aborting."
    exit 1
fi
# set up 9 spaces
osascript <<EOF
tell application "System Events"
    key code 18 using {control down}
    repeat 8 times
        delay 0.1
        key code 124 using {control down}
        key code 18 using {control down}
    end repeat
end tell
EOF
# Disable the animation when switching spaces
defaults write com.apple.dock workspaces-swoosh-animation-off -bool true
# Restart Dock to apply the changes
killall Dock
# call install_brew script
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
chmod +x "$DIR/install_brew"
"$DIR/install_brew"
