#!/bin/bash

brew install bash
echo "/opt/homebrew/bin/bash" | sudo tee -a /etc/shells && chsh -s /opt/homebrew/bin/bash
## iterm2
brew install --cask iterm2
## jq
brew install jq
## yq
brew install yq
## fzf 
brew install fzf
## ripgrep
brew install ripgrep
## node
brew install node
## tmux
brew install tmux
## neovim
brew install neovim
## web browser
brew install --cask arc
## notes
brew install --cask obsidian
# aerospace - window/space manager
brew install --cask nikitabobko/tap/aerospace
brew install --cask font-jetbrains-mono-nerd-font
brew install watch
brew install go-task
brew install bat
brew install eza
brew install starship
brew install bash-completion
