#!/bin/bash

function create_symlink() {
  local source_path=$1
  local target_path=$2
  if [ ! -e "$target_path" ]; then
    ln -s "$source_path" "$target_path"
  else
    echo "already exists: file or link at $target_path"
  fi
}


delete_symlink_if_exists() {
    local symlink=$1
    if [ -L "$symlink" ]; then
        rm "$symlink"
        echo "Symlink $symlink deleted."
    else
        echo "No need to delete $symlink - does not exist."
    fi
}

delete_symlink_if_exists "$HOME/.tmux.conf"
delete_symlink_if_exists "$HOME/.local/tmux_sessionizer.bash"
delete_symlink_if_exists "$HOME/.bashrc"
delete_symlink_if_exists "$HOME/.bash_profile"
delete_symlink_if_exists "$HOME/.config"
delete_symlink_if_exists "$HOME/.aerospace"
delete_symlink_if_exists "$HOME/.gitmux.conf"
delete_symlink_if_exists "$HOME/.vimrc"
create_symlink "$HOME/.dotfiles/tmux.conf" "$HOME/.tmux.conf"
create_symlink "$HOME/.dotfiles/bash_profile" "$HOME/.bash_profile"
create_symlink "$HOME/.dotfiles/bashrc" "$HOME/.bashrc"
create_symlink "$HOME/.dotfiles/config" "$HOME/.config"
create_symlink "$HOME/.dotfiles/aerospace" "$HOME/.aerospace"
create_symlink "$HOME/.dotfiles/gitmux.conf" "$HOME/.gitmux.conf"
create_symlink "$HOME/.dotfiles/vimrc" "$HOME/vimrc"
create_symlink "$HOME/.dotfiles/tmux_sessionizer.bash" "$HOME/.local/bin/tmux_sessionizer.bash"
create_symlink "$HOME/.dotfiles/gitignore_global" "$HOME/.gitignore_global"
chmod +x "$HOME/.local/bin/tmux_sessionizer.bash"



mkdir -p $HOME/.config/tmux/sessions
# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true
# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false
# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0
# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false
# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
# Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5
# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0
# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0
defaults write -g com.apple.swipescrolldirection -bool false

## homebrew
sudo curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
if [ ! -f /opt/homebrew/bin/brew ]; then
    echo "No file found at /opt/homebrew/bin/brew"
    exit 1
fi
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
if ! command -v brew &> /dev/null; then
    echo "homebrew could not be found. aborting."
    exit 1
fi
# Disable the animation when switching spaces
defaults write com.apple.dock workspaces-swoosh-animation-off -bool true
# Restart Dock to apply the changes
killall Dock
# call install_brew script
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
chmod +x "$DIR/install_brew"
"$DIR/install_brew"
