#!/bin/bash

OS=$(uname)

if [[ "$OS" == *"CYGWIN"* || "$OS" == *"MINGW"* || "$OS" == *"MSYS"* ]]; then
  echo "stop using windows."
  exit 1
fi

## config symlinks
ln -s "$HOME/.dotfiles/.config" "$HOME/.config"
ln -s "$HOME/dotfiles/.tmux.conf" "$HOME/.tmux.conf"

case "$OS" in
  'Linux')
    echo "Linux is not supported yet - exiting."
    exit 1
    ;;
  'Darwin')
    chmod +x ./inst_macos
    ./inst_macos
    chmod +x ./source_macos
    ./source_macos
    ;;
  *)
    echo "Unknown operating system: $OS - exiting."
    exit 1
    ;;
esac
