#!/bin/bash

OS=$(uname)

if [[ "$OS" == *"CYGWIN"* || "$OS" == *"MINGW"* || "$OS" == *"MSYS"* ]]; then
  echo "stop using windows."
  exit 1
fi

# determine script directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

## config symlinks
ln -s "$HOME/dotfiles/.tmux.conf" "$HOME/.tmux.conf"

case "$OS" in
  'Linux')
    echo "Linux is not supported yet - exiting."
    exit 1
    ;;
  'Darwin')
    chmod +x "$DIR/inst_macos"
    "$DIR/inst_macos"
    chmod +x "$DIR/source_macos"
    "$DIR/source_macos"
    ;;
  *)
    echo "Unknown operating system: $OS - exiting."
    exit 1
    ;;
esac
