#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OS=$(uname)

case "$OS" in
  'Linux')
    echo "Linux is not supported yet - exiting."
    exit 1
    ;;
  'Darwin')
    echo "setting up osx"
    "$SCRIPT_DIR/source_macos"
    ;;
  'CYGWIN'*|'MINGW'*|'MSYS'*)
    echo "Why would you use windows?"
    exit 1
    ;;
  *)
    echo "Unknown operating system: $OS - exiting."
    exit 1
    ;;
esac


